In [41]:
# User instructions: import the myHF2LI and magnet objects for the sagnac interferometer





# patch the old packages calling visa
# this is a hack to make the old packages work with pyvisa

#############################################################################################################################
import pyvisa

# Simulate the `visa` module as an alias for `pyvisa`
import sys

# Create a fake 'visa' module, which is essentially an alias for pyvisa
sys.modules['visa'] = pyvisa

# Optionally, map all attributes from pyvisa to visa (this is technically unnecessary because the alias works)
for attr in dir(pyvisa):
    setattr(sys.modules['visa'], attr, getattr(pyvisa, attr))

#############################################################################################################################


# Lock in

In [1]:
from aparatus.sagnac3 import myHF2LI


2025-01-02 13:44:43,554 - WARNING - Failed to import vxi11 package, which is required for the VXI11Adapter


sagnac3.0: no owon


In [12]:
myHF2LI.sigouts[1].amplitudes[7-1](0)

In [9]:
myHF2LI.ac(0.005)

0.0049591442805807535

In [40]:
myHF2LI.dem(3)["x"]

array([-8.74757918e-08])

In [5]:
myHF2LI.get_vout(1,6)

TypeError: unsupported operand type(s) for +: 'Node' and 'str'

In [6]:
from pymeasure.instruments.zurich import HF2LI
pyHF2LI = HF2LI(8005, 1, 18338)

In [13]:
[pyHF2LI.get_vout(1,a) *10 for a in range(8)]

[0.0,
 0.0,
 0.0,
 0.09994583088555059,
 0.0049591442805807535,
 0.0049591442805807535,
 0.9999923705472606,
 0.0]

# Stepper

In [1]:
from aparatus.sagnac3 import stepper

2025-01-06 22:26:32,018 - WARNING - Failed to import vxi11 package, which is required for the VXI11Adapter


In [ ]:
stepper.stepd(4,1) #neg Z


In [ ]:
import time
while True:
    time.sleep(0.2)
    stepper.stepu(4,1) #pos Z

# Keithley

In [1]:
from aparatus.sagnac3 import keith1
import time
time.sleep(50e-6)

2025-01-31 23:09:59,102 - WARNING - Failed to import vxi11 package, which is required for the VXI11Adapter


sagnac3.0: no owon


In [15]:
keith1.source_current = 1e-3
keith1.source_current = 0

In [4]:
# keith1.source_current = 1e-5
# time.sleep(1)
keith1.source_current = 0
keith1.resistance


9.91e+37

In [11]:
keith1.apply_current()
time.sleep(1)
print(f"done")


done


In [15]:
keith1.disable_source()

In [25]:
keith1.voltage[0]

4.695161e-05

In [19]:
keith2.voltage[0]

0.02306353

In [3]:


from pymeasure.instruments.keithley import Keithley2400
keithley = Keithley2400("GPIB::26")

In [12]:
# keithley.apply_current()                # Sets up to source current
# keithley.source_current_range = 10e-3   # Sets the source current range to 10 mA


In [4]:
keithley.source_current

-1e-06

In [14]:
keithley.voltage

0.02428094

In [10]:
keithley.compliance_voltage = 10        # Sets the compliance voltage to 10 V
keithley.source_current = 0             # Sets the source current to 0 mA
keithley.enable_source()                # Enables the source output

keithley.measure_voltage()              # Sets up to measure voltage

# keithley.ramp_to_current(5e-3)          # Ramps the current to 5 mA
print(keithley.voltage)   

8.592171e-05


In [7]:
# keith1 = Keithley2400("GPIB::26") #currently NI Max is reading as GPIB::26
# print(f"Check that output on Keithley is on")
keith1.enable_source()
keith1.measure_resistance()

# Pure Keithley

In [1]:
import sys
module_dir = r"C:\Users\luogroup\AppData\Roaming\Python\Python311\site-packages\pymeasure\instruments"
sys.path.append(module_dir)
from keithley.keithley2400 import Keithley2400 


In [2]:
keith1 = Keithley2400("GPIB::26")

In [5]:
keith1.source_current = 1e-3
keith1.source_current = 0

# OWON

In [11]:
import vds1022 as owon

dev = owon.VDS1022(debug=0)
dev.set_channel(owon.CH1, range='10v', probe='x1')
frames = dev.fetch()
print("%s Vrms" % frames.ch1.rms())

0.288 Vrms


In [18]:
dev.fetch().ch1.rms()

0.288

# Magnet

In [2]:
from aparatus.sagnac3 import atto

2025-02-05 14:25:05,468 - WARNING - Failed to import vxi11 package, which is required for the VXI11Adapter


sagnac3.0: no magnet aps100
sagnac3.0: no magnet aps100


In [ ]:
atto.

## Mag_HighZ

In [3]:
from aparatus.sagnac3 import mag_highZ , atto
mag_highZ.connect_highZ()

Connected to APS100 on COM4
Connected to APS100 on COM5
Not zeroing Bx and By, because if useful, you were already screwed.
disconnecting from x for safety
Disconnected from APS100


In [4]:
mag_highZ.setSafe_wait_highZ(-9.5)

 currently Bz= -18.75
waiting for mag_highZ for 5.211931228637695
 currently Bz= -18.0
waiting for mag_highZ for 6.422222375869751
 currently Bz= -18.717
waiting for mag_highZ for 7.632461071014404
 currently Bz= -18.691
waiting for mag_highZ for 8.84216022491455
 currently Bz= -18.677
waiting for mag_highZ for 10.051120519638062
 currently Bz= -18.555
waiting for mag_highZ for 14.467267513275146
 currently Bz= -18.407
waiting for mag_highZ for 15.677505016326904
 currently Bz= -18.358
waiting for mag_highZ for 16.887242317199707
 currently Bz= -18.306
waiting for mag_highZ for 18.09561276435852
 currently Bz= -18.177
waiting for mag_highZ for 20.30528497695923
 currently Bz= -18.022
waiting for mag_highZ for 26.32196545600891
 currently Bz= -17.84
waiting for mag_highZ for 27.53033971786499
 currently Bz= -17.734
waiting for mag_highZ for 29.73965573310852
 currently Bz= -17.655
waiting for mag_highZ for 30.95224118232727
 currently Bz= -17.496
waiting for mag_highZ for 35.56454277038

### dumy high z

In [1]:
import sys
module_dir = r"D:\Github\SagnacOperatingSys\VecMagSagnac_control"
sys.path.append(module_dir)
from sagnac.custom_instruments import vectorMagnetFullUSB_highZ
mag_highZ = vectorMagnetFullUSB_highZ()
mag_highZ.connect_highZ()

Connected to APS100 on COM4
Connected to APS100 on COM5
Zeroing X magnet
Zeroing Y magnet
disconnecting from x for safety
Disconnected from APS100


In [3]:
mag_highZ.set_field_highZ(2.2)

In [2]:
mag_highZ.get_field_highZ()

2.0

## Mag normal

### middleman

In [1]:
from aparatus.sagnac3 import mag , atto
mag.connect()

2025-02-06 12:38:00,937 - WARNING - Failed to import vxi11 package, which is required for the VXI11Adapter


sagnac3.0: no owon
Connected to APS100 on COM4
Connected to APS100 on COM5
conecting. The field is 1.0


In [2]:
mag.B = 0
# mag.By

In [3]:
mag.setSafe_wait()

waiting for z to ramp down 4.6194446086883545
waiting for z to ramp down 16.443257808685303
waiting for z to ramp down 20.05832266807556
waiting for z to ramp down 27.27715826034546
waiting for z to ramp down 32.09376645088196
waiting for z to ramp down 35.707979917526245
waiting for z to ramp down 39.32174587249756
waiting for mag for 49.554864168167114
waiting for mag for 54.173022747039795


In [3]:
atto.sample.getTemperature()

1.7476

In [6]:
atto.pressures.getCryoInPressure()

851.3686460541853

In [ ]:
mag.B

In [5]:
mag.setSafe_wait_polar(0.1,90,1.27)
#+Bx is 0deg azimuthal, +By is 90deg azimuthal (90deg polar), -Bx is 180deg azimuthal, -By is 270deg azimuthal, +Bz is 0deg polar

waiting for mag for 7.9203832149505615
waiting for mag for 10.638896942138672
waiting for mag for 17.760546684265137
waiting for mag for 20.37754988670349
waiting for mag for 22.893893241882324


In [9]:
mag.phi_set

90

In [8]:
mag.setSafeWaitTheta(45)

waiting for mag for 3.917996883392334
waiting for mag for 11.038495063781738
waiting for mag for 14.656440496444702
waiting for mag for 19.676960229873657
waiting for mag for 23.295124769210815
waiting for mag for 26.91261124610901


In [3]:
mag.get_field_cartesian()

(0.05, 0.05, 0.07)

In [3]:
mag.setSafeWaitBz(0.1)

waiting for mag for 4.617025375366211
waiting for mag for 11.44048810005188
waiting for mag for 16.057036876678467
waiting for mag for 20.673805236816406


In [6]:
#+Bx is 0deg azimuthal, +By is 90deg azimuthal (90deg polar), -Bx is 180deg azimuthal, -By is 270deg azimuthal, +Bz is 0deg polar
mag.setSafe_wait_polar(0,0, 0) 
mag.get_field_polar()
mag.get_field_cartesian()

waiting for mag for 3.8175227642059326
waiting for mag for 6.433938264846802
waiting for mag for 10.052460670471191
waiting for mag for 13.668297052383423
waiting for mag for 17.283501148223877
waiting for mag for 19.899211883544922
waiting for mag for 26.718703508377075
waiting for mag for 29.33670473098755
waiting for mag for 32.95661425590515
waiting for mag for 36.77753925323486
waiting for mag for 40.39781594276428
waiting for mag for 44.215943336486816
waiting for mag for 46.83206486701965
waiting for mag for 50.45032215118408
waiting for mag for 53.065261125564575
waiting for mag for 56.680387020111084
waiting for mag for 62.298378705978394
waiting for mag for 64.91691780090332
waiting for mag for 68.53624868392944
waiting for mag for 72.35463881492615
waiting for mag for 75.9722101688385
waiting for mag for 78.58765530586243
waiting for mag for 82.20453023910522
waiting for mag for 88.8214955329895
waiting for mag for 93.43939638137817
waiting for mag for 96.05652666091919
wait

(0.0, 0.0, 0.0)

In [3]:
print(mag.B_set)
print(mag.phi_set)
print(mag.theta_set)

0.01
45
90


In [8]:
import numpy as np
np.arange(-3,3,0.25)

array([-3.  , -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  ,
       -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,
        1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75])

In [9]:
mag.setSafeWaitB = lambda b: mag.setSafe_wait_polar(b,mag.phi_set,mag.theta_set)
mag.setSafeWaitPhi = lambda phi: mag.setSafe_wait_polar(mag.B_set,phi,mag.theta_set)
mag.setSafeWaitTheta = lambda theta: mag.setSafe_wait_polar(mag.B_set,mag.phi_set,theta)

In [4]:
mag.setSafeWaitPhi(90)

In [11]:
mag.setSafeWaitTheta(0)

waiting for mag for 7.105042219161987
waiting for mag for 14.210082292556763


In [7]:
import numpy as np
mag.setSafeWaitPhi(np.pi/4)

KeyboardInterrupt: 

In [5]:
from aparatus.sagnac3 import mag, atto
satfield = [-2,-1,1,2]
mag.Bz = [satfield]
mag.Bz

[[-2, -1, 1, 2]]

In [3]:
from aparatus.sagnac3 import keith1, keith2, myHF2LI, mag     
mag.safeWaitCart(0,0,0)

This one is the same

In [1]:
from aparatus.sagnac3 import keith1, keith2, myHF2LI, mag     
# mag.safeWaitCart(0,0,0.1)
mag.set_field_cartesian(0,0,0)

2024-12-21 00:36:20,163 - WARNING - Failed to import vxi11 package, which is required for the VXI11Adapter


sagnac3.0: no magnet aps100
sagnac3.0: no owon


ImportError: cannot import name 'mag' from 'aparatus.sagnac3' (d:\Github\SagnacOperatingSys\MinimalSagnac\sagnacMultitool\aparatus\sagnac3.py)

In [12]:
def setXmag(bx): mag.safeWaitCart(bx,0,0)

In [13]:
setXmag(0.01)

In [5]:
mag.safeWaitCart(0,0,0)

In [17]:
mag.get_field_cartesian()[2]

0.0

In [5]:
print( atto.condenser.getTemperature() ) 
print( atto.vti.getTemperature() ) 
atto.sample.getTemperature()

3.9904
1.7358


2.1099

In [2]:
from aparatus.sagnac3 import myHF2LI

### hardcode

In [ ]:
import atto_device.CRYO2100 as cr

device = cr("192.168.1.1")
device.connect()
device.condenser.getTemperature()
from aparatus.drivers.magnet_usbCom import vectorMagnetFullUSB
import atto_device.CRYO2100 as cr
mag = vectorMagnetFullUSB()
mag.connect()

mag.safeWaitCart(0.01,0.01,0.02)

In [ ]:
# import sys
# module_dir = r"D:\Github\SagnacOperatingSys\VecMagSagnac_control"
# sys.path.append(module_dir)
# from sagnac.custom_instruments import vectorMagnetFullUSB
# mag = vectorMagnetFullUSB()
# mag.connect()

# Pulse Class Test

In [1]:
import sys
module_dir = r"D:\Github\SagnacOperatingSys\VecMagSagnac_control"
sys.path.append(module_dir)
from sagnac.pulse_measurement import Pulse

sagnac3.0: no owon


In [2]:
instrument = Pulse()

Check that output on Keithley is on


In [3]:
instrument.pulsecurrent = 1e-3

In [117]:
instrument.send_pulse(1e-3)

Sending 0.001 A for 0.001 second pulse
<class 'float'>
Type of source_current: <class 'float'>


In [5]:
import numpy as np

def hysteresis(npArray):
    return np.concatenate([npArray, npArray[::-1]])

hysteresis( np.arange(-2.5,2.5,0.25)+0.125 )

array([-2.375, -2.125, -1.875, -1.625, -1.375, -1.125, -0.875, -0.625,
       -0.375, -0.125,  0.125,  0.375,  0.625,  0.875,  1.125,  1.375,
        1.625,  1.875,  2.125,  2.375,  2.375,  2.125,  1.875,  1.625,
        1.375,  1.125,  0.875,  0.625,  0.375,  0.125, -0.125, -0.375,
       -0.625, -0.875, -1.125, -1.375, -1.625, -1.875, -2.125, -2.375])

In [1]:
from aparatus.sagnac3 import keith1 

sagnac3.0: no owon


In [3]:
keith1.source_current = 0

NameError: name 'mag' is not defined